chotot/chotot/urls.py
from django.contrib import admin
from django.urls import path, include
from login_register import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from post import views as PostView

urlpatterns = [
    path('', PostView.IndexView.as_view(), name = 'index'),
    path('timraovat/', PostView.PostListView.as_view(), name = 'search'),
    path('admin/', admin.site.urls),
    path('users/', include('login_register.urls')),
    path('post/', include('post.urls')),
    path('logout/',auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chotot/login_register/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login_register'

urlpatterns = [
    path('profile/<int:pk>', views.ProfileView.as_view(), name = 'profile'),
    path('profile/current', views.CurrentProfileView.as_view(), name = 'current'),
    path('register/', views.register_view, name = 'register'),
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True,template_name="login_register/dangnhap.html"),name='login'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('reset_password/',views.ResetPasswordCustom.as_view(), name = 'reset'),
    path('reset_password/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'login_register/reset_password_form.html',success_url='/users/login'), name='reset_confirm'),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(template_name = 'login_register/reset_password.html'), name = 'reset_done'),
]

chotot/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.CreatePostView.as_view(), name = 'dangtin'),
    path('<int:pk>', views.PostDetailView.as_view(), name = 'baitinchitiet'),
    path('update/<int:pk>', views.UpdatePostView.as_view(), name = 'capnhat'),
]

chotot/post/models.py
from django.db import models
from django.utils.timezone import now
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image

class Category(models.Model):
    name = models.CharField(max_length=255)
    pic = models.ImageField(upload_to='post/category', blank=False, default='post/category/default.jpg')
    def __str__(self):
        return self.name

class Brand(models.Model):
    name = models.CharField(max_length=255)
    def __str__(self):
        return self.name

TYPE_CHOICES = (
    ('mua','Mua'),
    ('ban', 'Bán')
)

STATE_CHOICES = (
    ('open','Mở'),
    ('close','Đóng'),
    ('wait','Đang chờ')
)

class Post(models.Model):
    title = models.CharField(max_length=255, blank=False)
    content = models.TextField()
    create_date = models.DateTimeField(default = now, editable = False)
    update_date = models.DateTimeField(default = now)
    price = models.IntegerField()
    state = models.CharField(max_length=6, choices=STATE_CHOICES, default='wait')
    type_post = models.CharField(max_length=6, choices=TYPE_CHOICES, default='ban')
    user = models.ForeignKey(User,on_delete = models.CASCADE, related_name='post')
    category = models.ForeignKey(Category,on_delete = models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete = models.CASCADE)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("post:baitinchitiet", kwargs={"pk": self.pk})

class Image(models.Model):
    post = models.ForeignKey(Post,on_delete = models.CASCADE, related_name='images')
    pic = models.ImageField(upload_to='post/pic', blank=False)
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    def __str__(self):
        return self.post.title

REPORT_CHOICES = (
    ('sensitive','Nội dung nhạy cảm'),
    ('scam','Lừa đảo'),
    ('duplicate','Trùng lặp'),
    ('sale','Hàng đã bán'),
    ('real','Thông tin không giống thực tế'),
    ('none','Khác'),
)

class ReportPost(models.Model):
    post = models.ForeignKey(Post,on_delete = models.CASCADE, related_name='report',)
    pic = models.ImageField(upload_to='post/report', blank=False)
    content = models.TextField(blank=False)
    type_report = models.CharField(max_length=10, choices=REPORT_CHOICES, default='none')
    create_date = models.DateTimeField(default = now, editable = False)
    def __str__(self):
        return self.post.title

chotot/post/views.py
from django.shortcuts import render,redirect
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models,form

@login_required()
def post(request):
    return render(request, 'post/dangtin.html')

class IndexView(ListView):
    model = models.Category
    context_object_name = 'category'
    template_name = 'main/trangchu.html'

class PostListView(ListView):
    context_object_name = 'posts'
    model = models.Post
    paginate_by = 10
    template_name = 'post/timraovat.html'
    def get_queryset(self):
        filter_title = self.request.GET.get('title') or ''
        filter_brand = self.request.GET.get('brand') or ''
        filter_time = self.request.GET.get('time') or ''
        filter_type = self.request.GET.get('type') or ''
        filter_category = self.request.GET.get('category') or ''
        order_by = self.request.GET.get('order_by') or '?'
        new_context = models.Post.objects.filter(
            title__contains=filter_title,category__name__contains=filter_category,
            brand__name__contains=filter_brand,type_post__contains=filter_type
        ).order_by(order_by)
        return new_context
    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['category'] = models.Category.objects.order_by('name')
        context['brand'] = models.Brand.objects.order_by('name')
        return context

class CreatePostView(LoginRequiredMixin,CreateView):
    form_class = form.PostForm
    model = models.Post
    template_name = 'post/post.html'
    def form_valid(self, form):
        files = self.request.FILES.getlist('pic')
        if form.is_valid() and len(files)>=3 and len(files)<5:
            self.object = form.save(commit=False)
            self.object.user = self.request.user
            self.object.save()
            for pic in files:
                photo = models.Image(post=self.object, pic=pic)
                photo.save()
            return super().form_valid(form)
        else:
            return super().form_invalid(form)
    def get_context_data(self, **kwargs):
        ctx = super(CreatePostView, self).get_context_data(**kwargs)
        ctx['form_image'] = form.ImageForm
        return ctx
    def get_success_url(self):
        return '/timraovat'

class UpdatePostView(UpdateView):
    form_class = form.PostFormUpdate
    model = models.Post
    template_name = 'post/post.html'
    def get_success_url(self):
        return '/timraovat'

class PostDetailView(DetailView):
    context_object_name = 'post'
    model = models.Post
    template_name = 'post/tinchitiet.html'
    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['form_report'] = form.ReportForm()
        return context
    def post(self, request, *args, **kwargs):
        post = models.Post.objects.get(pk=self.kwargs['pk'])
        content = request.POST['content']
        type_report = request.POST['type_report']
        pic = request.FILES['pic']
        report = models.ReportPost(post=post,content=content,type_report=type_report,pic=pic)
        report.save()
        return redirect('/post/'+str(self.kwargs['pk']))

chotot/templates/post/post.html
{% extends "post/post_base.html"%}
{% block body_block%}
<div>
  <div class="_36tG76896bvCZ9jTEqerrE">
    <div class="_3OM1ogaI9EXK1udHCHiMUc">
      <div class="container">
          {% if not form.instance.pk %}
          <div class="text-center"><strong>ĐĂNG TIN</strong></div>
          {% else %}
          <div class="text-center"><strong>SỬA BÀI ĐĂNG</strong></div>
          {% endif %}
          <br>
          <form class="" method="POST" enctype='multipart/form-data' style="width: 50%;
          text-align: -webkit-center;">
            {% csrf_token %}
            <table>
                {{form}}
                {{form_image}}
            </table> 
            <div class="footer navbar-fixed-bottom formFooter ">
              <div class="container">
                <div class="btn-group btn-group-justified">
                  <span style="vertical-align: middle;">
                    <input class="btn btn-lg btn-primary btn-primary-customized" type="submit" value="Submit">
                  </span>
                </div>
            </div>
          </div>
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

chotot/templates/post/post_base.html
{% extends "base.html"%}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static "css/timraovat.css"%}">
<link rel="stylesheet" href="{% static "css/text.css"%}">
<link rel="stylesheet" href="{% static "css/dangki.css"%}">
<link rel="stylesheet" href="{% static "css/dangtin.css"%}">
<link rel="stylesheet" href="{% static "css/tinchitiet.css"%}">
{% endblock %}

chotot/templates/post/timraovat.html
{% extends "post/post_base.html"%}
{% load static %}
{% load humanize %}
{% load my_tags %}
{% block body_block%}
<div class="panel panel-default">
  <div class="container">
    <header>
      <div id="rgpt-2" data-google-query-id="">
        <div>
          <img class="img-buyer" src="{% static "images/GamingCreator_Static1.2_728x90.png" %}" alt="" width="750px" height="100px">
        </div>
      </div>
      <div>
        <h1 itemprop="name" class="muaban"> <strong>Mua bán, rao vặt nhanh chóng, uy tín tại Speeding Shopping Toàn
            quốc</strong> </h1>
      </div>
    </header>

    <main>
      <div class="row no-margin">
        <div class="col-md-8">
          <form method="GET">
            <div class=" hrSofa">
              <input type="text" name="title" class="daymOP" autocomplete="off" placeholder="Tìm kiếm trên Chợ Tốt..." value="{{ request.GET.title }}">
            </div>
            <div class="row _3p">
              <div class="col-xs-12 undefined">
                <div class="row">
                  <div class=" col-xs-12">
                    <div class="col-xs-5 _aa">
                      <span itemprop="name" class="toanquoc">Thương hiệu</span>
                      <select class="form-control" name="brand">
                          <option value=""></option>
                        {% for brand in brand%}
                        <option value="{{brand.name}}">{{brand.name}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-xs-7 _aa">
                      <span itemprop="name" class="toanquoc">Bạn muốn</span>
                      <select class="form-control" name="type" default="">
                        <option value=""></option>
                        <option value="ban">Mua</option>
                        <option value="mua">Bán</option>
                      </select>
                    </div>
                    <div class="col-xs-5 _aa">
                      <span itemprop="name" class="toanquoc">Tất cả danh mục</span>
                      <select class="form-control" name="category">
                        <option value=""></option>
                        {% for categ in category%}
                        <option value="{{categ.name}}">{{categ.name}}</option>
                        {% endfor %}
                      </select>
                    </div>
                    <div class="col-xs-7 _aa">
                      <span itemprop="name" class="toanquoc">Sắp xếp theo</span>
                      <select class="form-control" name="order_by">
                        <option value=""></option>
                        <option value="price">Từ thấp đến cao</option>
                        <option value="-price">Từ cao đến thấp</option>
                        <option value="-update_date">Mới nhất</option>
                      </select>
                    </div>

                  </div>
                </div>
              </div>
            </div>
            <input class="button" type="submit" value="Tìm kiếm">
          </form>
          {% for post in posts%}
          {% if post.state == "open" and post.user.is_active%}
          <div class="pgjTolSNq4-L--tpQ7Xp5">
            <!-- mở div đăng tin -->
            <div class="ctStickyAdsListing">
              <h3 class="ctAdListingTitle">
                <li class="ctAdListingWrapper listView"><a rel="nofollow" class="ctAdListingItem" action="push"
                    href="{% url 'post:baitinchitiet' post.id %}">
                    <div class="ctAdLitingThumbnail"> <img alt="{{post.name}}"
                        class="lazyload thumbnailImageListing" src="{{post.images.all.0.pic.url}}">
                    </div>
                    <div class="ctAdListingBody">
                      <h3 class="ctAdListingTitle">{{post.title}}</h3>
                      <div class="ctAdListingUpperBody"><span class="ctAdListingPrice">
                          <span class="adPriceMobile320">{{post.price|intcomma}} đ</span></span>
                      </div>
                      <div class="cMFlmw">
                        <div class="adItemType">
                          <div class="cMFlmw"><i class="stickyAdIcon"></i><span>{{post.user.username}}</span></div><span
                            class="delimeter"></span>
                          <div class="cMFlmw"><i class="stickyAdIcon"></i><span>Bài viết được đăng cách đây
                              {{post.create_date|timesince}}</span>
                          </div>
                        </div>
                        <div class="clear"></div>
                      </div>
                    </div>
                  </a>
                </li>
            </div>
          </div>
          {% endif %}
          {% endfor %}
          {% if not posts%}
          <div style="text-align:center;">
              <svg width="100" height="100" id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="15.6 37.6 80 50">
                <path class="st0"
                  d="M85.6 52.8s-5.1-7-13.2-6.6c-8.3-11.4-14.7-1.4-14.7-1.4-.6-.4-1.4-.6-2.2-.6-.8 0-1.5.2-2.2.6 0 0-6.4-10-14.7 1.4-8.1-.4-13.2 6.6-13.2 6.6-4.9 3-8.2 8.4-8.2 14.5 0 9.4 7.6 17 17 17 8.5 0 15.6-6.3 16.8-14.5 0 0 1.3 1.7 4.1 1.7s4.6-1.7 4.6-1.7C60.9 78 68 84.2 76.5 84.2c9.4 0 17-7.6 17-17 .3-6-3-11.4-7.9-14.4zM33.9 79.5c-6.4 0-11.6-5.2-11.6-11.6 0-6.4 5.2-11.6 11.6-11.6s11.6 5.2 11.6 11.6c.1 6.4-5.2 11.6-11.6 11.6zm42.9 0c-6.4 0-11.7-5.2-11.7-11.6 0-6.4 5.2-11.6 11.7-11.6 6.4 0 11.6 5.2 11.6 11.6 0 6.4-5.2 11.6-11.6 11.6z">
                </path>
                <path class="st0"
                  d="M26.9 66.9c-.4-1-.6-2-.7-3-1.2 2.1-1.5 4.7-.6 7.1 1.6 4.3 6.5 6.5 10.8 4.9.9-.3 1.7-.8 2.4-1.4-5 .4-10-2.5-11.9-7.6zM70.7 66.9c-.4-1-.6-2-.7-3-1.2 2.1-1.5 4.7-.6 7.1 1.6 4.3 6.5 6.5 10.8 4.9.9-.3 1.7-.8 2.4-1.4-5 .4-10-2.5-11.9-7.6z">
                </path>
              </svg>
              <div class="alert alert-warning">Bạn chưa có tin đăng cá nhân nào đang bán, thử đăng bán ngay.</div>
            </div>
          {% endif %}
          <div style="text-align: center;">
            {% if is_paginated %}
            {% if page_obj.has_previous %}
              <a href="/timraovat?{% param_replace page=1 %}">First</a>
              {% if page_obj.previous_page_number != 1 %}
                <a href="?{% param_replace page=page_obj.previous_page_number %}">Previous</a>
              {% endif %}
            {% endif %}

          Page {{ page_obj.number }} of {{ paginator.num_pages }}

            {% if page_obj.has_next %}
              {% if page_obj.next_page_number != paginator.num_pages %}
                <a href="/timraovat?{% param_replace page=page_obj.next_page_number %}">Next</a>
              {% endif %}
              <a href="/timraovat?{% param_replace page=paginator.num_pages %}">Last</a>
            {% endif %}
            {% endif %}
          </div>
        </div> <!-- đóng col 8 -->

      </div>
    </main> <!-- đóng thẻ main -->
  </div>
</div><!--  -->
{% endblock %}

chotot/templates/post/tinchitiet.html
<!DOCTYPE html>
{% extends "post/post_base.html"%}
{% load humanize %}
{% block body_block%}
<div id="fb-root"></div>
<script async defer crossorigin="anonymous"
  src="https://connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v5.0"></script>
<main class="App__Main-fcmPPF dlWmGF">
  <article style="background-color: #f4f4f4;">
    <div class="container _1OmYs5J4aYBAERDzg-6W8a">
      <div class="row hKeDdA_G7No3HepOClD8G">
        <div class="iltDBORq0FT_OjmouT7Ui">
          <div class="ICOY-4hTuxlSCBsYzqBxM">
            <h1 class="_22kG1zbJ4D-6IUEgKvoifC col-xs-12 AdItem__Title-fFamiu ekmzk" itemprop="name">
              {{post.title}}
            </h1>
          </div>
          <div itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
            <div class="col-xs-12 adItemOfferWrapper">
              <div class="AdItem__PriceWrapper-iSokgh cEWkgd"><span class="oRSYZ0HPb2tHhHjpVp_2o"><span itemprop="price"
                    content="{{post.price}}">{{post.price|intcomma}} đ</span>
                </span></div>
            </div>
          </div>
        </div>
      </div>
      <div class="row no-gutter-sm-down">
        <div class="col-sm-8" style="padding-bottom: 10px;">
          <div id="myCarousel" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              {% for image in post.images.all%}
              <li data-target="#myCarousel" data-slide-to="{{ forloop.counter0 }}"></li>
              {% endfor %}
            </ol>
            <div class="carousel-inner">
              <div class="item active">
                <img class="img-carousel" src="{{post.images.all.0.pic.url}}">
              </div>
              {% for image in post.images.all|slice:"1:"%}
              <div class="item">
                <img class="img-carousel" src="{{image.pic.url}}">
              </div>
              {% endfor %}
            </div>
          </div>
          <meta property="og:url" content="https://quiet-citadel-98654.herokuapp.com/post/{{post.id}}" />
          <meta property="og:type" content="article" />
          <meta property="og:title" content="{{post.title}}" />
          <meta property="og:description" content="{{post.content}}" />
          <meta property="og:image" content="" />
          <div>
            <p itemprop="description" class="col-xs-12 text-justify _1No0Ndy5xkVdszNItBaiuv"
              style="white-space: pre-line;">{{post.content}}</p>
            <div class="col-xs-12 margin-top-10"><strong class="text-muted">Chia sẻ tin đăng này cho bạn
                bè:</strong>
              <div>
                <!-- API FACEBOOK dùng để chia sẻ -->
                <div class="fb-share-button" data-href="https://quiet-citadel-98654.herokuapp.com/post/{{post.id}}"
                  data-layout="button_count" data-size="large">
                  <a target="_blank"
                    href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fdevelopers.facebook.com%2Fdocs%2Fplugins%2F&amp;src=sdkpreparse"
                    class="fb-xfbml-parse-ignore">
                    Chia sẻ</a></div>
                <a class="button__A-fZIMtR iINXMo"><img alt="messenger"
                    src="https://static.chotot.com/storage/chotot-icons/svg/circle-messenger.svg" height="40"
                    width="40"></a><a class="zalo-share-button button__A-fZIMtR iINXMo"
                  data-href="https://www.chotot.com/tp-ho-chi-minh/quan-12/mua-ban-dat/58555161.htm#xtatc=INT-5-[share_ad_via_zalo]"
                  data-oaid="570044068386186227" data-layout="2" data-color="blue" data-customize="true"><img alt="zalo"
                    src="https://static.chotot.com/storage/chotot-icons/svg/circle-zalo.svg" height="40"
                    width="40"><iframe frameborder="0" allowfullscreen="" scrolling="no" width="0px" height="0px"
                    src="https://sp.zalo.me/plugins/share?dev=null&amp;color=blue&amp;oaid=570044068386186227&amp;href=https%3A%2F%2Fwww.chotot.com%2Ftp-ho-chi-minh%2Fquan-12%2Fmua-ban-dat%2F58555161.htm%23xtatc%3DINT-5-%5Bshare_ad_via_zalo%5D&amp;layout=2&amp;customize=true&amp;callback=null&amp;id=b6ba63ea-69cd-4fd8-b8ab-aa8c0b033ab2&amp;domain=www.chotot.com&amp;android=false&amp;ios=false"
                    style="position: absolute;"></iframe></a><span class="copy__Wrapper-heVYVQ kWRTkk"><a
                    class="button__A-fZIMtR iINXMo"><img alt="copy"
                      src="https://static.chotot.com/storage/chotot-icons/svg/circle-copylink.svg" height="40"
                      width="40"></a></span>
              </div>
              <div class="sc-fBuWsC jCqADI"><img class="sc-fMiknA grsVqK"
                  src="https://static.chotot.com.vn/storage/marketplace/shield-iconx4.png" alt="mua bán an toàn">
                <div class="sc-dVhcbM jQCtce"><em>
                    <!-- react-text: 1588 -->Tin đăng này đã được kiểm duyệt. Nếu gặp vấn đề, vui lòng báo cáo tin
                    đăng hoặc liên hệ CSKH để được trợ giúp.&nbsp;
                    <!-- /react-text --><a target="_blank" rel="noopener"
                      href="http://trogiup.chotot.com/ban-hang-tai-chotot-vn/kiem-duyet-tin/tai-sao-chotot-vn-duyet-tin-truoc-khi-dang/?utm_source=chotot&amp;utm_medium=user_protection&amp;utm_campaign=user_protection_ad_view">Xem
                      thêm ››</a></em></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-4 visible-md visible-lg visible-xl _1E45evYilkAmIgtle77ZQk">
          <div>
            <div></div>
            <div class="" style="">
              <div class="_3mb4oCiyoOiRy41U3DhZcs">
                <div class="styles__UserProfileInfoWrapper-fAdrVE jQEbod"><a
                    class="styles__ProfileWrapper-dPhSlC bWGbBK" href="{% url 'login_register:profile' post.user.id%}"
                    target="_blank">
                    <img src="{{post.user.profile.pic.url}}"
                      class="img-thumbnail img-circle _3r1LxPzm9N9CZVK8hYBlze _38Q-ZJPwiUyqL82cU4XpN6 ">
                    <div class="styles__NameBounder-fVrffo fqYgiV">
                      <div class="styles__FlexDiv-gecxmb juHLCK">
                        <div class="styles__NameDiv-fClOhj dzrPXg"><b>
                            <b>{{post.user.username}}</b></div><button
                          class="styles__SecondaryButton-kJMwTe iluGAh styles__BaseBtn-bLaJmp kFdpfu">Xem
                          trang</button>
                      </div>
                      <div class="styles__StatusOnlineDiv-EFyjL ijoFhp"><span
                          class="styles__OnlineBullet-dVkMwj VeeSf">•</span> Lần cuối đăng nhập:
                        {{post.user.last_login|timesince}} trước
                      </div>
                    </div>
                  </a>
                </div>
                <div class="_1NPt6YwpCxTsRRk89MWcQe">
                  <div class="_1qSLCB8OdSh-qqBU-8hsY9">
                    <div class="btn-block _172F-2PuOv67wKHZRmWZv_">
                      <div class="sc-gisBJw ikcTlv">
                        <div class="sc-kjoXOD icTLCU">
                          <div class="sc-cHGsZl iTxwzU"><span><img class="sc-TOsTZ bnAkpx"
                                src="https://static.chotot.com.vn/storage/chotot-icons/svg/white-phone.svg">
                            </span><span>{{post.user.profile.phone}}</span></div>
                        </div>
                      </div>
                    </div>
                  </div>

                  {% if post.user == user%}
                  <div style="text-align: center;">
                    <div class="sc-cIShpX drOAqa">
                      <a class="sc-kafWEX dbdoNV" href="{% url 'post:capnhat' pk=post.pk%}" target="_blank">
                        <div class="sc-feJyhm ccHAWL"><span><img class="sc-iELTvK fjYNlE"
                              src="https://icon-library.net/images/chnage-icon/chnage-icon-10.jpg"></span><span>Sửa
                            bài viết</span></div>
                      </a>
                    </div>
                  </div>
                  {% endif %}
                  <div class="_1qSLCB8OdSh-qqBU-8hsY9" style="text-align: center;">
                    <div class="btn-block _172F-2PuOv67wKHZRmWZv_">
                      <div class="sc-gisBJw ikcTlv">
                        <div class="sc-cHGsZl iTxwzU">
                          {% if not user == post.user%}
                          <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                            Báo cáo bài viết
                          </button>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="_1qSLCB8OdSh-qqBU-8hsY9 _2yFnwriywXbN31B7bl3L4 text-muted small">
                    <div class="col-xs-12 margin-top-10" style="padding-top: 30%;">
                      <div>
                        <div class="SafeTips__SafeTipsWrapper-gWgMGO guGpFY">
                          <div><img alt="safe tips" class="pull-left" width="100"
                              src="https://st.chotot.com/storage/images/tips/1_PTY.png">
                            <div class="mb-0 SafeTips__TipText-iJoGDM gYDniF">KHÔNG NÊN đặt cọc nếu chưa xác định được
                              chủ nhà.</div><a class="pull-left"
                              href="https://trogiup.chotot.com/mua-hang-tai-chotot-vn/meo-mua-hang-tim-viec/meo-khi-thue-phong/?utm_source=chotot&amp;utm_medium=ad_view&amp;utm_campaign=safety_tip_adview"
                              target="_blank">Tìm hiểu thêm »</a>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </article>
</main>

<!-- The Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title">Báo cáo bài viết</h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <form action="" method="POST" enctype='multipart/form-data'>
        <div class="modal-body">
          {%csrf_token%}
          <table>
            {{form_report}}
          </table>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="submit" class="btn btn-warning">Report bài viết</button>
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>
      </form>

    </div>
  </div>
</div>
{% endblock %}