chotot/chotot/urls.py
from django.contrib import admin
from django.urls import path, include
from login_register import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from post import views as PostView

urlpatterns = [
    path('', PostView.IndexView.as_view(), name = 'index'),
    path('timraovat/', PostView.PostListView.as_view(), name = 'search'),
    path('admin/', admin.site.urls),
    path('users/', include('login_register.urls')),
    path('post/', include('post.urls')),
    path('logout/',auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chotot/login_register/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login_register'

urlpatterns = [
    path('profile/<int:pk>', views.ProfileView.as_view(), name = 'profile'),
    path('profile/current', views.CurrentProfileView.as_view(), name = 'current'),
    path('register/', views.register_view, name = 'register'),
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True,template_name="login_register/dangnhap.html"),name='login'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('reset_password/',views.ResetPasswordCustom.as_view(), name = 'reset'),
    path('reset_password/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'login_register/reset_password_form.html',success_url='/users/login'), name='reset_confirm'),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(template_name = 'login_register/reset_password.html'), name = 'reset_done'),
]

chotot/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.CreatePostView.as_view(), name = 'dangtin'),
    path('<int:pk>', views.PostDetailView.as_view(), name = 'baitinchitiet'),
    path('update/<int:pk>', views.UpdatePostView.as_view(), name = 'capnhat'),
]

chotot/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load humanize %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> Speed Shopping</title>
    <link rel="stylesheet" href="{% static "css/base.css"%}">
    {% block style%}
    {% endblock %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

<body>
    <nav class="navbar" role="navigation">
        <div class="container">
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <li class="navbar-nav">
                        <a href="{% url 'index'%}" style="
                        padding-right: 0px;
                        padding-left: 0px;
                        padding-bottom: 5%;
                        padding-top: 5%;">
                            <img src="{% static "images/chotot.png"%}" alt="" border="0" srcset="" width="auto" height="35px">
                        </a>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'search'%}">Tìm rao vặt</a></li>
                    <li><a href="{% url 'login_register:current'%}">Người dùng</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'logout'%}">Đăng Xuất</a></li>
                    {% else %}
                    <li><a href="{% url 'login_register:login'%}">Đăng Nhập</a></li>
                    {% endif %}
                    <li>
                        <div class="button">
                            <a href="{% url 'post:dangtin'%}"><button style="
                                margin-top: 10px;
                            " type="button" class="btn btn-warning">ĐĂNG TIN</button></a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block body_block%}
    {% endblock %}
</body>

</html>