chotot/chotot/urls.py
from django.contrib import admin
from django.urls import path, include
from login_register import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from post import views as PostView

urlpatterns = [
    path('', PostView.IndexView.as_view(), name = 'index'),
    path('timraovat/', PostView.PostListView.as_view(), name = 'search'),
    path('admin/', admin.site.urls),
    path('users/', include('login_register.urls')),
    path('post/', include('post.urls')),
    path('logout/',auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chotot/login_register/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'login_register'

urlpatterns = [
    path('profile/<int:pk>', views.ProfileView.as_view(), name = 'profile'),
    path('profile/current', views.CurrentProfileView.as_view(), name = 'current'),
    path('register/', views.register_view, name = 'register'),
    path('login/', views.LoginView.as_view(redirect_authenticated_user=True,template_name="login_register/dangnhap.html"),name='login'),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('reset_password/',views.ResetPasswordCustom.as_view(), name = 'reset'),
    path('reset_password/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = 'login_register/reset_password_form.html',success_url='/users/login'), name='reset_confirm'),
    path('reset_password/done', auth_views.PasswordResetDoneView.as_view(template_name = 'login_register/reset_password.html'), name = 'reset_done'),
]

chotot/post/urls.py
from django.urls import path
from . import views

app_name = 'post'

urlpatterns = [
    path('create/', views.CreatePostView.as_view(), name = 'dangtin'),
    path('<int:pk>', views.PostDetailView.as_view(), name = 'baitinchitiet'),
    path('update/<int:pk>', views.UpdatePostView.as_view(), name = 'capnhat'),
]

chotot/login_register/models.py
from django.db import models
from django.core.cache import cache 
import datetime
from chotot import settings
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(max_length=11,unique=True, blank=False)
    balance = models.IntegerField(default = 0)
    pic = models.ImageField(upload_to='pic', blank=False, default="pic/default.jpg")
    address = models.TextField(blank=True)
    def __str__(self):
        return self.user.username

chotot/login_register/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from login_register.models import Profile

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    re_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    re_email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    class Meta():
        model = User
        fields = ('username','email','re_email','password','re_password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            're_email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            're_password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
        help_texts = {
            'username': None,
            'email': None,
        }

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        re_email = all_clean_data['re_email']
        password = all_clean_data['password']
        re_password = all_clean_data['re_password']

        if email != re_email :
            raise forms.ValidationError("Email bạn nhập chưa đúng")

        if password != re_password :
            raise forms.ValidationError("Password bạn nhập chưa đúng")

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone','pic')
        widgets = {
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
        }
    def clean(self):
        all_clean_data = super().clean()
        phone = all_clean_data['phone']
        if (phone[0:3].lower() not in ['086','096','097','098','089','090','093','088','091','094','099','092','056','058'] and len(phone)==10)\
            and (phone[0:4].lower() not in ['0162','0163','0164','0165','0166','0167','0168','0169','0120','0121','0122','0126','0128','0123','0124','0125','0127','0129','0199'] and len(phone)==11):
            raise forms.ValidationError("Số điện thọai của bạn không hợp lệ, phải đăng ký bằng số diện thoại di động")

class UpdateUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    re_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ('password','re_password','first_name','last_name')
        widgets = {
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            're_password': forms.PasswordInput(attrs={'class': 'form-control'}),
        }
    def clean(self):
        all_clean_data = super().clean()
        password = all_clean_data['password']
        re_password = all_clean_data['re_password']

        if password != re_password :
            raise forms.ValidationError("Password bạn nhập chưa đúng")

class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('address','pic')
        widgets = {
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        }

chotot/login_register/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.views import LoginView,PasswordChangeView,PasswordResetView
from django.http import HttpResponse
from login_register.models import Profile
from login_register.forms import ProfileForm,UserForm,UpdateProfileForm,UpdateUserForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView,UpdateView
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate
from django.contrib.sites.shortcuts import get_current_site
from . import models
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.core.mail import EmailMessage


class ProfileView(DetailView):
    context_object_name = 'nguoidung'
    model = User
    template_name = 'login_register/current.html'
    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        context['form_profile'] = UpdateProfileForm()
        context['form_user'] = UpdateUserForm()
        return context
    def post(self, request, *args, **kwargs):
        user_form = UpdateUserForm(data=request.POST)
        profile_form = UpdateProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = User.objects.get(pk=request.user.id)
            user.profile.address = profile_form.cleaned_data['address'] if profile_form.cleaned_data['address'] else user.profile.address
            profile = user.profile
            profile.pic = request.FILES.get('pic') if request.FILES.get('pic') else profile.pic
            user.first_name = user_form.cleaned_data['first_name'] if user_form.cleaned_data['first_name'] else user.first_name
            user.last_name = user_form.cleaned_data['last_name'] if user_form.cleaned_data['last_name'] else user.last_name
            user.set_password(user_form.cleaned_data['password'])
            user.save()
            profile.save()
            return redirect('login_register:current')
        else:
            return HttpResponse('Password không đúng')


class CurrentProfileView(LoginRequiredMixin, ProfileView):
    context_object_name = 'nguoidung'
    def get_object(self):
        return self.request.user
    
def register_view(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = ProfileForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.is_active = False
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'pic' in request.FILES:
                profile.pic = request.FILES['pic']
            profile.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('login_register/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid':urlsafe_base64_encode(force_bytes(user.pk)),
                'token':account_activation_token.make_token(user),
            })
            to_email = user_form.cleaned_data.get('email')
            email = EmailMessage(
                        mail_subject, message, to=[to_email]
            )
            email.send()
            registered = True
            return render(request,'login_register/register_done.html',{'message':'Thank you for register we will redirect you in 5 seconds or you can click this link'})
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request,'login_register/dangky.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return render(request,'login_register/register_done.html',{'message':'Thank you for your email confirmation. Now you can login your account.'})
    else:
        return HttpResponse('Activation link is invalid!')

class ResetPasswordCustom(PasswordResetView):
    template_name = 'login_register/reset_password.html'
    email_template_name='login_register/password_reset_email.html'
    success_url='/users/login'
    redirect_authenticated_user=True

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            confirm_email = form.cleaned_data['email']
            if not User.objects.filter(email=confirm_email):
                return render(request,'login_register/reset_password.html',{'message':'Email của bạn không có trong database vui lòng nhập lại','form':form})
            else:
                return super().form_valid(form)

chotot/templates/login_register/acc_active_email.html
{% csrf_token %}
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'login_register:activate' uidb64=uid token=token %}
{% endautoescape %}

chotot/templates/login_register/current.html
{% extends "base.html"%}
{%load static%}
{% load humanize %}
{% block style%}
<link rel="stylesheet" href="{% static "css/tinchitiet.css"%}">
<link rel="stylesheet" href="{% static "css/timraovat.css"%}">
<link rel="stylesheet" href="{% static "css/text.css"%}">
{% endblock %}
{% block body_block%}
<div class="main-content">
  <div class="container WrapperContainer">
    <div class="breadcrumWrapper">
      <ul class="sc-jzJRlG cIiMVT">
        <li class="sc-cSHVUG jbltJC"><a href="{% url 'index'%}"" class=" sc-kAzzGY eZQMkE">Chợ Tốt</a></li>
        <li class="sc-cSHVUG jbltJC"><a class="sc-kAzzGY llFQGq">Trang cá nhân của {{nguoidung.username}}</a></li>
      </ul>
    </div>
    <div class="PaperContainer contactInfo false">
      <div class="PaperInfoWrapper"
        style="color:rgba(0, 0, 0, 0.87);background-color:#ffffff;transition:all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;box-sizing:border-box;font-family:Verdana, Arial, sans-serif;-webkit-tap-highlight-color:rgba(0,0,0,0);box-shadow:0 1px 2px rgba(0,0,0,.1);border-radius:2px">
        <div class="row">
          <div class="col-12 col-md-6 BasicInfo">
            <div class="AvatarWrapper"><img
                style="color:#ffffff;background-color:rgb(188, 188, 188);user-select:none;display:inline-flex;align-items:center;justify-content:center;font-size:40px;border-radius:50%;height:80px;width:80px"
                size="80" alt="Ngọc Hoa" src="{{nguoidung.profile.pic.url}}">
            </div>
            <div class="InfoWrapper">
              <div class="col-8 col-md-12">
                <div>
                  <span class="name">{{nguoidung.username}}</span>
                </div>
                <div>
                  <label for="">Họ và tên:</label> {{nguoidung.first_name}} {{nguoidung.last_name}}
                </div>
                <div>
                  <label for="">Địa chỉ:</label> {{nguoidung.profile.address}}
                </div>
                <div>
                  <label for="">Điện thoại:</label> {{nguoidung.profile.phone}}
                </div>
                {% if user == nguoidung%}
              <div class="UltiRow">
                  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">
                    Chỉnh sửa trang cá nhân
                  </button>
              </div>
              {% endif %}
              </div>
            </div>
          </div>
          <div class="col-12 col-md-6 ExtraInfo">
            <div class="itemRow sc-dVhcbM dGzVUk"><img
                src="https://static.chotot.com.vn/storage/marketplace/common/pf_rating_icon.svg">Đánh giá:&nbsp;<div
                class="ratingInfo  sc-fMiknA kIKSvV"><span>Chưa có đánh giá</span></div>
            </div>
            <div class="itemRow"><img class="" src="{% static "images/calendar.png"%}" height="16" alt="">Ngày tham gia:
              &nbsp; <span>{{nguoidung.date_joined|date:'d/m/Y'}}</span></div>
            <div class="itemRow"><img class="" src="{% static "images/calendar.png"%}" height="16" alt="">Online:
              &nbsp; <span>{{ nguoidung.last_login|timesince }} trước</span></div>
            <div class="itemRow"><img class="" src="{% static "images/check.png"%}" height="16" alt="">Đã cung cấp:
              &nbsp;
              <div class="icon active infoIcon"><img src="{% static "images/facebook_active.png"%}" height="26">
              </div>
              <div class="icon default infoIcon"><img src="{% static "images/address_default.png"%}" height="26">
              </div>
              <div class="icon active infoIcon"><img src="{% static "images/phone_active.png"%}" height="26">
              </div>
              <div class="icon default infoIcon"><img src="{% static "images/email_default.png"%}" height="26">
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
    <div class="indexPage PaperContainer">
      <table class="PaperWrapper table"
        style="color:rgba(0, 0, 0, 0.87);background-color:#ffffff;transition:all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;box-sizing:border-box;font-family:Verdana, Arial, sans-serif;-webkit-tap-highlight-color:rgba(0,0,0,0);box-shadow:0 1px 2px rgba(0,0,0,.1);border-radius:2px">
        <thead>
          <tr>
            <th><h4 class="TitleHeading">Đang bán</h4></th>
            <th><h4 class="TitleHeading">Tình trạng</h4></th>
          </tr>
        </thead>
        <tbody>
          {% if not nguoidung.post.all%}
            <svg width="100" height="100" id="Layer_1" xmlns="http://www.w3.org/2000/svg" viewBox="15.6 37.6 80 50">
              <path class="st0"
                d="M85.6 52.8s-5.1-7-13.2-6.6c-8.3-11.4-14.7-1.4-14.7-1.4-.6-.4-1.4-.6-2.2-.6-.8 0-1.5.2-2.2.6 0 0-6.4-10-14.7 1.4-8.1-.4-13.2 6.6-13.2 6.6-4.9 3-8.2 8.4-8.2 14.5 0 9.4 7.6 17 17 17 8.5 0 15.6-6.3 16.8-14.5 0 0 1.3 1.7 4.1 1.7s4.6-1.7 4.6-1.7C60.9 78 68 84.2 76.5 84.2c9.4 0 17-7.6 17-17 .3-6-3-11.4-7.9-14.4zM33.9 79.5c-6.4 0-11.6-5.2-11.6-11.6 0-6.4 5.2-11.6 11.6-11.6s11.6 5.2 11.6 11.6c.1 6.4-5.2 11.6-11.6 11.6zm42.9 0c-6.4 0-11.7-5.2-11.7-11.6 0-6.4 5.2-11.6 11.7-11.6 6.4 0 11.6 5.2 11.6 11.6 0 6.4-5.2 11.6-11.6 11.6z">
              </path>
              <path class="st0"
                d="M26.9 66.9c-.4-1-.6-2-.7-3-1.2 2.1-1.5 4.7-.6 7.1 1.6 4.3 6.5 6.5 10.8 4.9.9-.3 1.7-.8 2.4-1.4-5 .4-10-2.5-11.9-7.6zM70.7 66.9c-.4-1-.6-2-.7-3-1.2 2.1-1.5 4.7-.6 7.1 1.6 4.3 6.5 6.5 10.8 4.9.9-.3 1.7-.8 2.4-1.4-5 .4-10-2.5-11.9-7.6z">
              </path>
            </svg>
            <div class="alert alert-warning">Bạn chưa có tin đăng cá nhân nào đang bán, thử đăng bán ngay.</div>
          {%else%}
            {% for post in nguoidung.post.all%}
            {% if post.state != 'close'%}
              <tr>
                <td>
                  <div class="pgjTolSNq4-L--tpQ7Xp5">
                    <div class="ctStickyAdsListing">
                      <h3 class="ctAdListingTitle">
                        <li class="ctAdListingWrapper listView"><a rel="nofollow" class="ctAdListingItem" action="push"
                            href="{% url 'post:baitinchitiet' post.id %}">
                            <div class="ctAdLitingThumbnail">
                              <img alt="" class="lazyload thumbnailImageListing" src="{{post.images.all.0.pic.url}}">
                            </div>
                            <div class="ctAdListingBody" style="
                            padding-left: 40px;
                            text-align: left;">
                              <h3 class="ctAdListingTitle">{{post.title}}</h3>
                              <div class="ctAdListingUpperBody"><span class="ctAdListingPrice">
                                  <span class="adPriceMobile320">{{post.price|intcomma}} đ</span></span>
                              </div>
                              <div class="cMFlmw">
                                <div class="adItemType">
                                  <div class="cMFlmw"><i
                                      class="stickyAdIcon"></i><span>{{post.create_date|timesince}}</span>
                                  </div>
                                </div>
                                <div class="clear"></div>
                              </div>
                            </div>
                          </a>
                        </li>
                    </div>
                  </div>
                </td>
                {%if post.state == 'open'%}
                  <td style="text-align: center;
                  vertical-align: middle;
                  font-size: x-large;
                  color: green">
                        Đang được bày bán
                  </td>
                {%elif post.state == 'wait'%}
                  <td style="text-align: center;
                  vertical-align: middle;
                  font-size: x-large;
                  color: red">
                        Đang chờ duyệt
                  </td>
                {%endif%}
              </tr>
              {% endif %}
            {%endfor%}
          {%endif%}
        </tbody>
      </table>
    </div>
    <div><a tabindex="0" href="{% url 'post:dangtin' %}"
      style="border: 1px solid rgb(254, 153, 0); box-sizing: border-box; display: inline-block; font-family: Verdana, Arial, sans-serif; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); cursor: pointer; text-decoration: none; margin: 0px 0px 10px; padding: 0px; outline: none; font-size: inherit; font-weight: inherit; position: relative; vertical-align: middle; height: 36px; line-height: 30px; min-width: 100%; color: rgba(0, 0, 0, 0.87); transition: all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms; border-radius: 3px; user-select: none; overflow: hidden; background-color: rgba(0, 0, 0, 0); text-align: center;">
      <div><span class="span-dangtin"
          style="position: relative; padding-left: 16px; padding-right: 16px; vertical-align: middle; letter-spacing: 0px; text-transform: uppercase; font-weight: bold; font-size: 13px; color: rgb(254, 153, 0);">Đăng
          tin</span></div>
    </a>
  </div>
  </div>
</div>
<div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">
  
        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Chỉnh sửa trang cá nhân</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
  
        <!-- Modal body -->
        <form action="" method="POST" enctype='multipart/form-data'>
          <div class="modal-body">
            {%csrf_token%}
            <table>
              {{form_profile}}
              {{form_user}}
            </table>
          </div>
  
          <!-- Modal footer -->
          <div class="modal-footer">
            <button type="submit" class="btn btn-warning">Cập nhật</button>
            <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          </div>
        </form>
  
      </div>
    </div>
  </div>
{% endblock %}

chotot/templates/login_register/dangky.html
<!DOCTYPE html>
{% extends "base.html"%}
{%load static%}
{% block style%}
<link rel="stylesheet" href="{% static "css/dangki.css"%}">
{% endblock %}
  {% block body_block%}
  <div class="panel panel-dangki">
    <div class="form-title" data-reactid="44">ĐĂNG KÝ</div>
    <form data-reactid="45" method="POST" enctype='multipart/form-data'>
      {% csrf_token %}
      {{user_form.as_p}}
      {{profile_form.as_p}}
      <div class="form-group" data-reactid="48">
        <button type="submit" class="btn dangki" data-reactid="49">ĐĂNG KÝ</button>
      </div>
      <div data-reactid="50" class="chu-dangki">
        Bấm vào đăng ký nghĩa là bạn đã đọc và đồng ý với
        <a href="#" data-reactid="52"> Điều khoản sử dụng của Chợ Tốt </a>
      </div>
      <p class="dangki">Bạn đã có tài khoản <a href="{% url 'login_register:login'%}">Đăng nhập</a></p>
    </form>
  </div>
  {% endblock %}

chotot/templates/login_register/dangnhap.html
<!DOCTYPE html>
{% extends "base.html"%}
{%load static%}
{% block style%}
<link rel="stylesheet" href="{% static "css/dangki.css"%}">
{% endblock %}
  {% block body_block%}
    <div class="panel panel-dangki">
    <div class="form-title" data-reactid="44">ĐĂNG NHẬP</div>
    <form data-reactid="45" method="POST">
      {% csrf_token %}
        <div class="form-group" style="text-align: center;">
          {{form.as_p}}
        </div>
      <div class="form-group" data-reactid="48">
        <button type="submit" class="btn dangnhap" data-reactid="49">ĐĂNG NHẬP</button>
        <a href="{% url 'login_register:reset'%}">
          <button type="button" class="btn quenmatkhau">Quên mật khẩu?</button>
        </a>
        <a href="{% url 'login_register:register'%}">
            <button  type="button" class="btn dangki" data-reactid="59">Đăng ký</button>
        </a>
        <a href="{% url 'login_register:reset'%}">
            <button  type="button" class="btn resend">Chưa nhận được mail đăng ký</button>
        </a>
      </div>
    </form>
  </div>
  {% endblock %}

chotot/templates/login_register/password_reset_email.html
{% autoescape off %}
Hi {{ user.email }},
Please click on the link to confirm your reset password,
{{ protocol }}://{{ domain }}{% url 'login_register:reset_confirm' uidb64=uid token=token %}
{% endautoescape %}

chotot/templates/login_register/register_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register done</title>
    <meta http-equiv="refresh" content="5;url={% url 'login_register:login' %}" />
</head>
<body>
    {{message}}
    <a href="{% url 'login_register:login' %}">Click here to redirect</a>
</body>
</html>

chotot/templates/login_register/reset_password.html
<!DOCTYPE html>
{% extends "base.html"%}
{%load static%}
{% block style%}
<link rel="stylesheet" href="{% static "css/dangki.css"%}">
{% endblock %}
  {% block body_block%}
    <div class="panel panel-dangki">
    <div class="form-title" data-reactid="44">LẤY LẠI MẬT KHẨU</div>
    <form data-reactid="45" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="form-group" data-reactid="48">
        <p style="text-align:center;">{{message}}</p>
        <button type="submit" class="btn dangki" data-reactid="49">Lấy lại mật khẩu</button>
      </div>
    </form>
  </div>
  {% endblock %}

chotot/templates/login_register/reset_password_form.html
<!DOCTYPE html>
{% extends "base.html"%}
{%load static%}
{% block style%}
<link rel="stylesheet" href="{% static "css/dangki.css"%}">
{% endblock %}
  {% block body_block%}
    <div class="panel panel-dangki">
    <div class="form-title" data-reactid="44">NHẬP LẠI MẬT KHẨU</div>
    <form data-reactid="45" method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="form-group" data-reactid="48">
        <button type="submit" class="btn dangki" data-reactid="49">NHẬP lại mật khẩu</button>
      </div>
    </form>
  </div>
  {% endblock %}